from enum import Enum, auto


class PlanValidationType(Enum):
    TERRAFORM = auto()
    JENKINS = auto()


class DeploymentOptions(Enum):
    DOCKERIZED_DEPLOYMENT = "Dockerized Deployments (Containerization)"
    KUBERNETES_DEPLOYMENT = "Kubernetes-Orchestrated Deployment"
    VM_DEPLOYMENT = "MI/VM Image-Based Deployment"


class LoraStatus(Enum):
    STARTING = "LORASTATUS_STARTING"
    INTENT_DETECTED = "LORASTATUS_INTENT_DETECTED"
    RETRIEVING_USER_PREFERENCES = "LORASTATUS_RETRIEVING_USER_PREFERENCES"
    RETRIEVING_PROJECT_DETAILS = "LORASTATUS_RETRIEVING_PROJECT_DETAILS"
    GENERATING_PLAN = "LORASTATUS_GENERATING_PLAN"
    GENERATED_PLAN = "LORASTATUS_GENERATED_PLAN"
    FAILED = "LORASTATUS_FAILED"
    COMPLETED = "LORASTATUS_COMPLETED"
    GATHERING_DATA = "LORASTATUS_GATHERING_DATA"


class GraphStatus(Enum):
    INITIALIZE = "GRAPHSTATUS_INITIALIZE"
    COMPLETED = "GRAPHSTATUS_COMPLETED"
    FAILED = "GRAPHSTATUS_FAILED"


class ExcecutionStatus(Enum):
    INITIALIZE = "EXCECUTION_INITIALIZE"
    PROCESSING = "EXCECUTION_PROCESSING"
    WAITING_FOR_INPUT = "EXCECUTION_WAITING_FOR_INPUT"
    COMPLETED = "EXCECUTION_COMPLETED"
    FAILED = "EXCECUTION_FAILED"
    ABORTED = "EXCECUTION_ABORTED"


class Preconndition(Enum):
    TEST_COVERAGE = "TEST_COVERAGE"
    CODE_QUALITY = "CODE_QUALITY"
    BUILD_STATUS = "BUILD_STATUS"
